import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'bun:test'
import { cflAc, cflPred, intraPred, prepareIntraEdges } from '../src/av1/ipred'

/**
 * Reference vectors generated by running dav1d's actual compiled
 * prepare_intra_edges + prediction kernels (ipred_tmpl.c) over deterministic
 * random planes. Covers every mode (incl. directional angle deltas, filter
 * intra, and CFL), many block shapes, positions, and edge-flag combinations.
 */
interface PredVector {
  op: 'P' | 'C'
  mode?: number
  angle?: number
  alpha?: number
  tw: number
  th: number
  x4: number
  y4: number
  w4: number
  h4: number
  ef?: number
  smf?: number
  fe?: number
  seed: number
  cbw4?: number
  cbh4?: number
  wpad?: number
  hpad?: number
  outMode: number
  hash: string
  first: number[]
}

const vectors = JSON.parse(
  readFileSync(join(import.meta.dir, 'fixtures', 'ipred-vectors.json'), 'utf8'),
) as PredVector[]

// Fills a plane with the same deterministic LCG stream the reference harness
// used. Inlined (rather than a per-byte closure call) so the ~300M-iteration
// plane regeneration across all vectors stays well under the CI test timeout on
// slower x64 runners; the produced bytes are identical to the original closure.
function fillPlane(plane: Uint8Array, seed: number): number {
  let rng = seed >>> 0
  for (let i = 0; i < 256 * 256; i++) {
    rng = (Math.imul(rng, 1664525) + 1013904223) >>> 0
    plane[i] = (rng >>> 8) & 0xFF
  }
  return rng
}

function fillPlaneFrom(plane: Uint8Array, rngIn: number): number {
  let rng = rngIn >>> 0
  for (let i = 0; i < 256 * 256; i++) {
    rng = (Math.imul(rng, 1664525) + 1013904223) >>> 0
    plane[i] = (rng >>> 8) & 0xFF
  }
  return rng
}

function fnv(plane: Uint8Array, off: number, stride: number, w: number, h: number): string {
  // matches the reference harness (which used a truncated FNV-1a basis)
  let hash = 1469598103934665603n
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      hash ^= BigInt(plane[off + y * stride + x])
      hash = (hash * 0x100000001B3n) & 0xFFFFFFFFFFFFFFFFn
    }
  }
  return hash.toString(16).padStart(16, '0')
}

describe('intra prediction vs dav1d reference vectors', () => {
  it('matches all prediction vectors bit-exactly', () => {
    const stride = 256
    const plane = new Uint8Array(256 * 256)
    const plane2 = new Uint8Array(256 * 256)
    const edge = new Uint8Array(260)
    const ac = new Int16Array(32 * 32)
    let checked = 0

    for (const v of vectors) {
      if (v.op === 'P') {
        fillPlane(plane, v.seed)
        const dstOff = v.y4 * 4 * stride + v.x4 * 4
        const prep = prepareIntraEdges(
          v.x4,
          v.x4 > 0,
          v.y4,
          v.y4 > 0,
          v.w4,
          v.h4,
          v.ef!,
          plane,
          dstOff,
          stride,
          v.mode!,
          v.angle!,
          v.tw,
          v.th,
          v.fe!,
          edge,
          128,
        )
        if (prep.mode !== v.outMode)
          throw new Error(`vector ${checked}: mode ${prep.mode} != ${v.outMode} (${JSON.stringify(v)})`)
        intraPred(
          prep.mode,
          plane,
          dstOff,
          stride,
          edge,
          128,
          v.tw * 4,
          v.th * 4,
          prep.angle | v.smf! | (v.fe! << 10),
          4 * v.w4 - 4 * v.x4,
          4 * v.h4 - 4 * v.y4,
        )
        const hash = fnv(plane, dstOff, stride, v.tw * 4, v.th * 4)
        if (hash !== v.hash) {
          throw new Error(
            `vector ${checked}: hash mismatch for ${JSON.stringify(v)}: `
            + `got ${hash}, first bytes ${Array.from(plane.slice(dstOff, dstOff + 8)).join(',')} want ${v.first.join(',')}`,
          )
        }
      }
      else {
        const rng = fillPlane(plane, v.seed)
        fillPlaneFrom(plane2, rng)
        cflAc(
          ac,
          plane,
          v.y4 * 8 * stride + v.x4 * 8,
          stride,
          v.wpad!,
          v.hpad!,
          v.cbw4! * 4,
          v.cbh4! * 4,
          1,
          1,
        )
        const dstOff = v.y4 * 4 * stride + v.x4 * 4
        const prep = prepareIntraEdges(
          v.x4,
          v.x4 > 0,
          v.y4,
          v.y4 > 0,
          v.w4,
          v.h4,
          0,
          plane2,
          dstOff,
          stride,
          0, // DC_PRED
          0,
          v.tw,
          v.th,
          0,
          edge,
          128,
        )
        expect(prep.mode).toBe(v.outMode)
        cflPred(prep.mode, plane2, dstOff, stride, edge, 128, v.tw * 4, v.th * 4, ac, v.alpha!)
        const hash = fnv(plane2, dstOff, stride, v.tw * 4, v.th * 4)
        if (hash !== v.hash) {
          throw new Error(
            `cfl vector ${checked}: hash mismatch for ${JSON.stringify(v)}: `
            + `got ${hash}, first bytes ${Array.from(plane2.slice(dstOff, dstOff + 8)).join(',')} want ${v.first.join(',')}`,
          )
        }
      }
      checked++
    }
    expect(checked).toBe(vectors.length)
  }, 30000)
})
