import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'bun:test'
import { itxfmAdd } from '../src/av1/itx'
import { SCANS, TX_TYPE_CLASS } from '../src/av1/tables'

/**
 * Reference vectors generated by dav1d's compiled itxfm_add C functions over
 * deterministic pseudo-random coefficients; each vector pins one (tx, txtp,
 * eob) combination bit-exactly (FNV-1a hash of the reconstructed block).
 */
interface ItxVector {
  tx: number
  txtp: number
  eob: number
  seed: number
  hash: string
  cfZeroed: boolean
  first: number[]
}

const vectors = JSON.parse(
  readFileSync(join(import.meta.dir, 'fixtures', 'itx-vectors.json'), 'utf8'),
) as ItxVector[]

const W = [4, 8, 16, 32, 64, 4, 8, 8, 16, 16, 32, 32, 64, 4, 16, 8, 32, 16, 64]
const H = [4, 8, 16, 32, 64, 8, 4, 16, 8, 32, 16, 64, 32, 16, 4, 32, 8, 64, 16]

function fnv1a64(dst: Uint8Array, w: number, h: number): string {
  const prime = 0x100000001B3n
  const mask = 0xFFFFFFFFFFFFFFFFn
  // matches the generator harness's offset basis (a truncated form of the
  // canonical FNV-1a basis 0xcbf29ce484222325)
  let hash = 1469598103934665603n
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      hash ^= BigInt(dst[y * 64 + x])
      hash = (hash * prime) & mask
    }
  }
  return hash.toString(16).padStart(16, '0')
}

describe('itxfmAdd vs dav1d reference vectors', () => {
  it(`matches all ${vectors.length} vectors bit-exactly`, () => {
    let failures = 0
    const messages: string[] = []

    for (const vec of vectors) {
      const { tx, txtp, eob, seed } = vec
      const w = W[tx]
      const h = H[tx]
      const sw = Math.min(w, 32)
      const sh = Math.min(h, 32)
      const slw = 31 - Math.clz32(sw) - 2
      const slh = 31 - Math.clz32(sh) - 2

      // LCG identical to the C harness
      let rng = seed >>> 0
      const next = (): number => {
        rng = (Math.imul(rng, 1664525) + 1013904223) >>> 0
        return rng >>> 8
      }

      const cf = new Int32Array(64 * 64)
      const cls = TX_TYPE_CLASS[txtp]
      for (let i = 0; i <= eob; i++) {
        let v = (next() % 2048) - 1024
        if (v === 0)
          v = 1
        let rc: number
        if (cls === 0) {
          rc = SCANS[tx][i]
        }
        else if (cls === 1) {
          rc = i
        }
        else {
          const x = i & ((4 << slw) - 1)
          const y = i >> (slw + 2)
          rc = (x << (slh + 2)) | y
        }
        cf[rc] = v
      }

      const dst = new Uint8Array(64 * 64)
      for (let y = 0; y < h; y++)
        for (let x = 0; x < w; x++)
          dst[y * 64 + x] = (x * 7 + y * 13 + seed) & 0xFF

      itxfmAdd(dst, 0, 64, cf, tx, txtp, eob)

      const hash = fnv1a64(dst, w, h)
      const first = Array.from(dst.subarray(0, Math.min(16, w)))
      let cfZeroed = true
      for (let i = 0; i < sw * sh; i++) {
        if (cf[i] !== 0) {
          cfZeroed = false
          break
        }
      }

      const ok = hash === vec.hash
        && cfZeroed === vec.cfZeroed
        && first.length === vec.first.length
        && first.every((b, i) => b === vec.first[i])
      if (!ok) {
        failures++
        if (messages.length < 10) {
          messages.push(
            `tx=${tx} txtp=${txtp} eob=${eob} seed=${seed}: `
            + `hash ${hash} vs ${vec.hash}, cfZeroed ${cfZeroed} vs ${vec.cfZeroed}, `
            + `first [${first.join(' ')}] vs [${vec.first.join(' ')}]`,
          )
        }
      }
    }

    if (failures > 0)
      throw new Error(`${failures}/${vectors.length} vectors failed:\n${messages.join('\n')}`)
    expect(failures).toBe(0)
  })
})
