import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'bun:test'
import { decodeSubexp, SymbolDecoder, SymbolEncoder } from '../src/av1/msac'

/**
 * Reference vectors generated by running dav1d's msac.c (the reference AV1
 * decoder's entropy coder) over deterministic random data and operations.
 * See the harness described in the repo history; the vectors pin our
 * implementation bit-exactly to the reference, including CDF adaptation.
 */
const vectors = JSON.parse(
  readFileSync(join(import.meta.dir, 'fixtures', 'msac-vectors.json'), 'utf8'),
) as { data: string, ops: { op: string, args: number[] }[], expected: string[] }

describe('SymbolDecoder vs dav1d reference vectors', () => {
  it('matches 3000 mixed decode operations bit-exactly', () => {
    const data = Uint8Array.from(atob(vectors.data), c => c.charCodeAt(0))
    const s = new SymbolDecoder(data, false)

    for (let i = 0; i < vectors.ops.length; i++) {
      const { op, args } = vectors.ops[i]
      const expected = vectors.expected[i]
      let actual: string
      if (op === 'S') {
        const n = args[0]
        const cdf = new Uint16Array(args.slice(1, n + 2))
        const v = s.decodeSymbol(cdf, 0, n)
        actual = `S ${v} | ${Array.from(cdf).join(' ')}`
      }
      else if (op === 'B') {
        actual = `B ${s.decodeBool(args[0])}`
      }
      else if (op === 'A') {
        const cdf = new Uint16Array(args)
        const v = s.decodeBoolAdapt(cdf, 0)
        actual = `A ${v} | ${cdf[0]} ${cdf[1]}`
      }
      else if (op === 'E') {
        actual = `E ${s.decodeBoolEqui()}`
      }
      else if (op === 'L') {
        actual = `L ${s.readLiteral(args[0])}`
      }
      else {
        actual = `X ${decodeSubexp(s, args[0], args[1], args[2])}`
      }
      if (actual !== expected)
        throw new Error(`vector ${i} (${op}): got "${actual}", want "${expected}"`)
    }
    expect(true).toBe(true)
  })
})

describe('SymbolDecoder basics', () => {
  it('reads past-the-end data as if padded (still terminates)', () => {
    const s = new SymbolDecoder(new Uint8Array([0x80]), true)
    for (let i = 0; i < 100; i++) {
      const b = s.decodeBoolEqui()
      expect(b === 0 || b === 1).toBe(true)
    }
  })

  it('does not adapt CDFs when updates are disabled', () => {
    const data = new Uint8Array([0xA7, 0x31, 0x99, 0x42])
    const cdf = new Uint16Array([20000, 10000, 5000, 0])
    const before = Array.from(cdf)
    const s = new SymbolDecoder(data, true)
    s.decodeSymbol(cdf, 0, 3)
    expect(Array.from(cdf)).toEqual(before)
  })
})

describe('SymbolEncoder round trips', () => {
  it('round-trips mixed adaptive and literal symbols', () => {
    const initial = new Uint16Array([25000, 17000, 9000, 0])
    const encCdf = initial.slice()
    const encoder = new SymbolEncoder(false)
    const expected: Array<{ kind: 'symbol' | 'bit', value: number }> = []

    for (let i = 0; i < 2000; i++) {
      if (i % 5 === 0) {
        const value = (i * 13) & 1
        encoder.encodeBoolEqui(value)
        expected.push({ kind: 'bit', value })
      }
      else {
        const value = (i * 17 + 3) & 3
        encoder.encodeSymbol(encCdf, 0, 3, value)
        expected.push({ kind: 'symbol', value })
      }
    }

    const decoder = new SymbolDecoder(encoder.finish(), false)
    const decCdf = initial.slice()
    for (const item of expected) {
      const actual = item.kind === 'bit'
        ? decoder.decodeBoolEqui()
        : decoder.decodeSymbol(decCdf, 0, 3)
      expect(actual).toBe(item.value)
    }
    expect(Array.from(decCdf)).toEqual(Array.from(encCdf))
  })

  it('round-trips literals and Golomb values with updates disabled', () => {
    const encoder = new SymbolEncoder(true)
    const literals = [[0, 1], [1, 1], [5, 3], [255, 8]] as const
    const golombs = [0, 1, 2, 7, 31, 300]
    for (const [value, bits] of literals)
      encoder.writeLiteral(value, bits)
    for (const value of golombs)
      encoder.writeGolomb(value)

    const decoder = new SymbolDecoder(encoder.finish(), true)
    for (const [value, bits] of literals)
      expect(decoder.readLiteral(bits)).toBe(value)
    for (const value of golombs)
      expect(decoder.readGolomb()).toBe(value)
  })
})
